import java.util.ArrayList;

public class Day12 {

    //Returns the number of corners a grid space contributes
    public static int corners(char[][] grid, Coord coord) {
        char c = grid[coord.getX()][coord.getY()];

        int corners = 0;



        Coord up = new Coord(coord.getX() - 1, coord.getY());
        Coord right = new Coord(coord.getX(), coord.getY() + 1);
        Coord down = new Coord(coord.getX() + 1, coord.getY());
        Coord left = new Coord(coord.getX(), coord.getY() - 1);

        //Checking the top left diagonal (the up and left squares)
        int d1 = 0;
        if (valid(grid, up)) {
            if (grid[up.getX()][up.getY()] == c) {
                d1 = d1 + 1;
            }
        }

        if (valid(grid, left)) {
            if (grid[left.getX()][left.getY()] == c) {
                d1 = d1 + 1;
            }
        }

        if (d1 == 0) {
            corners = corners + 1;
        }

        if (d1 == 2) {
            Coord s = new Coord(left.getX() - 1, left.getY());
            if (!valid(grid, s) || grid[left.getX() - 1][left.getY()] != c) {
                corners = corners + 1;
            }
        }

        //checking the bottom left diagonal
        int d2 = 0;
        if (valid(grid, left)) {
            if (grid[left.getX()][left.getY()] == c) {
                d2 = d2 + 1;
            }
        }

        if (valid(grid, down)) {
            if (grid[down.getX()][down.getY()] == c) {
                d2 = d2 + 1;
            }
        }

        if (d2 == 0) {
            corners = corners + 1;
        }

        if (d2 == 2) {
            Coord s = new Coord(left.getX() + 1, left.getY());
            if (grid[left.getX() + 1][left.getY()] != c) {
                corners = corners + 1;
            }
        }

        //Checking bottom right diagonal
        int d3 = 0;

        if (valid(grid, down)) {
            if (grid[down.getX()][down.getY()] == c) {
                d3 = d3 + 1;
            }
        }

        if (valid(grid, right)) {
            if (grid[right.getX()][right.getY()] == c) {
                d3 = d3 + 1;
            }
        }

        if (d3 == 0) {
            corners = corners + 1;
        }

        if (d3 == 2) {
            Coord s = new Coord(right.getX() + 1, right.getY());
            if (!valid(grid, s) || grid[right.getX() + 1][right.getY()] != c) {
                corners = corners + 1;
            }
        }

        //Checking top right diagonal
        int d4 = 0;

        if (valid(grid, right)) {
            if (grid[right.getX()][right.getY()] == c) {
                d4 = d4 + 1;
            }
        }

        if (valid(grid, up)) {
            if (grid[up.getX()][up.getY()] == c) {
                d4 = d4 + 1;
            }
        }

        if (d4 == 0) {
            corners = corners + 1;
        }

        if (d4 == 2) {
            Coord s = new Coord(right.getX() - 1, right.getY());
            if (!valid(grid, s) || grid[right.getX() - 1][right.getY()] != c) {
                corners = corners + 1;
            }
        }

        return corners;


    }

    public static int search(char[][] grid) {

        //All the points visited in the graph
        ArrayList<Coord> visitedAll = new ArrayList<Coord>();

        int cost = 0;

        for (int i = 0; i < grid.length; i++) {
            for (int j = 0; j < grid[0].length; j++) {
                Coord c = new Coord(i, j);
                if (!visitedAll.contains(c)) {
                    visitedAll.add(c);

                    ArrayList<Coord> island = new ArrayList<Coord>();



                    char c1 = grid[c.getX()][c.getY()];


                    int p = search1(island, visitedAll, c, grid, c1);

                    int sides = 0;

                    for (Coord square : island) {
                        sides = sides + corners(grid, square);
                    }



                    int size = island.size();


                    cost = cost + size*sides;
                }
            }
        }

        return cost;

    }

    /**
     * Returns the perimeter of the island from a starting coordinate
     * @param island the coordinates found so far in the island
     * @param visitedAll the coordinates visited in the grid
     * @param current the current coordinate
     * @return the perimeter of the island
     */
    public static int search1(ArrayList<Coord> island, ArrayList<Coord> visitedAll, Coord current, char[][] grid, char c) {

        if (current.getX() >= grid.length || current.getY() >= grid[0].length ||current.getX() < 0 || current.getY() < 0 || grid[current.getX()][current.getY()] != c) {
            return 1;
        }

        if (island.contains(current)) {
            return 0;
        }

        island.add(current);
        visitedAll.add(current);

        Coord c1 = new Coord(current.getX() - 1, current.getY());
        int perimeter = search1(island, visitedAll, c1, grid, c);

        Coord c2 = new Coord(current.getX(), current.getY() + 1);
        perimeter = perimeter + search1(island, visitedAll, c2, grid, c);

        Coord c3 = new Coord(current.getX() + 1, current.getY());
        perimeter = perimeter + search1(island, visitedAll, c3, grid, c);

        Coord c4 = new Coord(current.getX(), current.getY() - 1);
        perimeter = perimeter + search1(island, visitedAll, c4, grid, c);

        return perimeter;
    }





    //Tests whether a coord is valid or not
    public static boolean valid(char[][] grid, Coord c) {
        return c.getX() >= 0 && c.getY() >= 0 && c.getX() < grid.length && c.getY() < grid[0].length;
    }

    public static class Coord {
        private int x;

        private int y;

        public Coord(int x, int y) {
            this.x = x;
            this.y = y;
        }

        public int getY() {
            return y;
        }

        public int getX() {
            return x;
        }

        @Override
        public boolean equals(Object obj) {
            try {
                Coord c = (Coord) obj;

                return c.getX() == this.getX() && c.getY() == this.getY();

            } catch (ClassCastException e) {
                return false;
            }
        }

        @Override
        public String toString() {
            return "(" + x + "," +  y + ")";
        }
    }

    public static char[][] parseInput(String input) {
        String[] s = input.split("\n");

        char[][] grid = new char[s.length][s[0].length()];

        for (int i = 0; i < s.length; i++) {
            String row = s[i];
            for (int j = 0; j < s[0].length(); j++) {
                grid[i][j] = row.charAt(j);
            }
        }

        return grid;
    }


    public static void main(String[] args) {
        String input = "EEEEEEEEUUURRRRNRMMOJOOOOSSSSSSSSSSSSSEERRWWOOOOOOOOOOTTTTTCCCCCCRRYYYYYGGGGGGGGGGGGAAAAAAAAAAAAAPPPPMMMUUUUUUUUUURRRRRRRRRRRCCCCCCCHHHHHHHH\n" +
                "EEEEEEEEEURRRRRRRMROOOOOOSSSSSSESEEEEEEEEEWWWOOOOOOTTTTTTTTCCCCCCYYYYYYYGGGGGGGGGGGGAAAAAAAAAAAAAAAAPMMMMUUUUUUUUURRRRRRRRRCRCCCCCCHHCHHHHHH\n" +
                "EEEEEEEEEEUURRRRRRROOOOOOOOOSSEEEEEEEEEEEWWWWOWOOWOOTTTTTTTCCCCCCYYYYYGGGGGGGGGGGGGGAAAAAAAAAAAAPAAPPMMMMMMUMUUUUUURRRRRRCCCCCCCCCCCCCHHHHHH\n" +
                "EEEEEEEEEEUURRRRROOOOOOYYOOSSEEEEEEEEEEEDWWWWWWWWWOOTTTTTTTCCCCCYYUYGGGGGGGGGGGGGGGAAAAAAAAAAAAAPPPPPMBMMMMMMMUUUUUURRRRRRCCCCCCCCCCCCHHHHHH\n" +
                "EEEEEEEEEUUURRROOOOOOOOOOOOSSEEEEEEEEEEEWWWWWWWWWWOWWQTTTCCCCCCCCYUGGGGGGGGGGGGGGGGAAAAAAAAAAAAAPPPPPPBBMMMIMMUUUULLRRRRRRRCCCCCCCCCCCCHHHHH\n" +
                "EEEEEEEEEUUUEROOOOOOOOOOOFFEEEEEEEEEEEWWWWRWWWWWWWWWWWTTTTTSCCCCCCCGGGGGGGGGGGGGGGAAAAAAAAAAAAAPPPPPPPPPPMPPPPPCCLLLLLRAAAACCCAAACCCCCCCHHHH\n" +
                "EEEEEEEEEEEEERRRRRROOOOOOOFEEEHEEEEEEEWWWWWWWWWWWWWWWWWTTHSSCSCCCCCCGGGGGGGGGGGGGGAAAQQAAAAAAAAAAPPPPPPPPPPPPPPPCCLLLLAAAAAAAAAAACCCCHHHHHHH\n" +
                "EEEEEEEEEEEERRRRRRROOOOOOFFFFEHEEEEEEEEWWGWWWWWWWWWWWWWWOSSSCSSSCWWWWWGGGGGGGGGGGGGAXQQQQQQAQQAAPPPPPPPPPPPPPPPPCCLLLLLLAAAAAAAAACCCCHHHHHHH\n" +
                "RRRREREEEEEEERRRROOOOOOOOFFFFFEEEEEEEEEAAWWWWWWWWWWWWWWWSSSSCSSSSSSWWWWGGGGGGGGGGXXXXQQQQQQQQQAQQQOPPPPPPPPPPPPPPCLOLLLLLAAAAAAAAALLAHHHHHHH\n" +
                "RRRRRREESEERRRRRRRROOCOOOFFHHHAEEEEEEEAAAWWWWWWWWWWWWWSSSSSSSSSSSSKWWKWKGGGGXXGGGXXXZQQQQQQQQQQQQPPPPPPPPPPPPPPPPCCLLLLLAAAAAAAAAAAAAHHHHHHH\n" +
                "KRRRRGSSSSRRLLRRRRROOOOYOFHHHHHIEFEEEEEARJWWRWWWWQWDDDDSSSSSSSSPKHKWWKKKKGGGGXXXGXXXQQQQQQQQQQQQQQHPPPPPPMPPMMPCCCCLLLLLAAAAAAAAAAAAAAAHHHHH\n" +
                "RRRRRRSSSLLLLLRRRROOOOOYOOORHHHHEEEXXHHRRRRRRWWWWWDDDDDSSSSSSSSSKKKKKKKKQGQGQXXXGXXXXQQQQQQQQQQQQQQAQPPPMMPPMMMMMCCLLLLLLAAAAAAAAAAAAAAHHHHH\n" +
                "RCCSRRSSSSSLRRRRRROOOOOOOPOHHHHHHHHXXXHRRRRRRRWWWWDDDDDSSSSISSSQKKKKKKKKQQQQQXXXXXXXXXQQQQQQQQQQQQQQQPPPMMMMMMMMCCCCWLLLAAAAAAAAAAAAAAHHHHHH\n" +
                "RRRSSSSSSSSSSSSROOOOOOOOOOOHHHHHHHHXXHHRRRRRRRWDDDDDDDDSIIIIIIYQKKKYYYYKYQQQQXXXXXXXKKQQQQQQQQQQQQQQPPPMMMMMMMMMCCWWWWWWWAAAAAAAAAAAHHHHHHHH\n" +
                "SRSSSSGGGGGGSSSSOOOOOOOOOOOOHHHHHHHHHHHHHCRRRRRDDDDDBBBBBIIIIIYYYVKYYYYKYYQYQXXXXXXXXKQQQQQQQQQQNNNPPPPMMMMMMMMMCCWWWWWWWWWWWAAAAAAAIIIHHHHI\n" +
                "SSSSSSSGGGGGSSSSOOOOOOOOOOOHHHHHHHHHHHHHCCRRRRRDDDBBBBFBBIIIIYYYYYKYYYYYYYYYQXXXXXXXXXXXXXQQQQQQQQQPPPMMMMMMMMMMWWWWWWWWWWWWWAAAAIIIIIHHHHII\n" +
                "SSSSSSSGGGGGSSSSOOOOOOOOOOOHHHHHHHOHHHHQQQRQRDDDDBBBBBBBBBBBBYYYYYYYYYYYYYYYXXXXXXXXXXXXXXQQQQQTTTTTMMMMMMMMMMMMWWWWWWWWWWWEEAIIAIIIIIIHHHII\n" +
                "SSSSSSSSGGGGSSSSSSOOOOOOOOOOHHOOOOOHHHQQQQQQQDDBBBBBBBBBBBBIBVYYYYYYYYYYYYYYJXXXXXXXXXXXXQQQQQQQMMTTMMMMMMMMMMMMMWWWWWWWWWWWEEIIAIIIIIIIIIII\n" +
                "SSSSSGGGGGGGSSSSSSSOOOOOOOOOOOOOOOOHXQQQQQQQDDDDBBBBBBBBBBBBBBBQYYYYYYYYYYYJJXXXXXXXXXXXXXQQQPPQMTTTMMMMMMMMMMMMMWWWWWWWWWCCCEIIIIIIIIIIIIII\n" +
                "SSSSSGGGGGGGSSSSSSSOOOOOOOOOOOOOOOOHQQQQQQQZZZDDBBBBBBBBBBBBBBQQYYYEYYYYYYYYYXXXXXXXXXXXXXNPPNPMMMMMMMMMMMMMMMMMMMMWWWWWWCCCCEBIIIIIIIIIIIII\n" +
                "SSSSSSSSGGGGSSSSSSSOOOOOWOOOOOOOOOOQQQQQQQZZZZZDBBBBBBBBBBBSBQQQYYYEYYYYYYYFFXXXXXXXXXMMXNNNNNNNNNMNNMMMMMMMMMSMMWWWWWEEEEEEEEBBIIIIIIIIIIII\n" +
                "SSSSSSSGGGGGGSSSSSOOOOWWWOOOOXOXXOOQQQQQQZZZZZZBBYBBBBBBBBBBBQQEEEEEMYYYIVVIFXXXXXXMMMMMMNNNNNNNNNNNNNNNMMMMMMMMWWWWWEEEEEEEEEEEDINIIIIIIIII\n" +
                "SSSSSSSGGGGSSSSSSSSOOJWWWWWWOXXXXQQQQQQQQQZZZZZBBBBBBBBBBBBBBBEEEEEEEYYYIIIIIIXLMMXMMMMMMNNNNNNNNNNNNNNNMMMMMMWWWWWWWEEEEEEEEEDDDIIIIIIIIIII\n" +
                "SSSSSSSSSSSSSSSSSSSSSJWWWWWWXXXXXXQQQQQQZQZZZZZZZBBBBBBBBBBBBBEEEEEEYYYIIIFIIILLMMXMMMMMMNNNNNNNNNNNNNNNUMMMMMWWWWWWWWEEEEEEEEEEDIIIIMMMMMII\n" +
                "SSSSSSSSSSSYYYSSSSSSSWWWWWWWWWXXXXQQQQQDZZZZZZZZBBBBBBBBBBBBWWEEEEEEEEEFIIFLLLLLLMMMMMMMMMMNNNNNNNNENNNNNMWWWWWWWWWWWWEEEEEEEEEDDDDMMMMMMMMI\n" +
                "SSSSSSSSSSSSYSSSSWSWWWWWWWWWWWWXXXXXQQQZZZZZZZZZZZBBBBBBBBBBWWWYYEEEEDEFIILLLLLLLLMLMMMMMMMMNNNNNNNEENNNNNWWWWWWWWWWWWEEEEEEEEEEDDDDMMMMMMMI\n" +
                "SSSSSSSSSYYYYSSSSWWWWWWWWWWWWWWWXXXXQQQXZZZXZZZZZZBBBBBBWWWWWYYYYYEEIIIIILLLLLLLLLLLLMMMMMMNNNNNNNNEJEJWLWWWWWWWWWWWWEEEEEEEEEEEDDMMMMMMMMMI\n" +
                "SSSSSSSSSQYYYYSSSWWWWWWWWWWWWWWWWXXXXQXXXXXXZZZZZZZZZZZWWWWWWWYYYYEIIIIIIUILLLLLLLLLMMMMMMMMNKNNHHNEEEEWWWWWAAWWWWWWREEEEEEEEEDDDDMMMMMMMMMM\n" +
                "SSSSSPSSSYYYYYYSSWWWWWWWWWWWWWWWWQXXXXXXXXXXXZZZZZZZZWWWWWWWWWWWYYYYIIIIIIILLLLLLLLLMMMMMMMMHHNHHHHEEEEEAAAAAAAAWWWRRRXXXEEEEEDDDDMMMMMMMMMM\n" +
                "SWMSSMSSGYYYYYYYSSWWWWWWWWWWLWWWQQQXXXXXXFZZZZZZZZZZZZZZWWWWWIIIIIIIIIIIIIILLLLLLLLMMMMMMMMHHHHHHEHEEEEEIAAAAAAAWWRRRRXXXXXXXMMMMMMMMMMMMMMM\n" +
                "MMMSMMMYYYYYYYYYYUWWWWWLLLLLLLLLQQQXXXXXXFZZZZZZZZZZZZZZWKWWWWIIIIIIIIIIIIILLLLLLLMMMMMMMMMHHHHHEEEEEEEEEAAAAAAAWWRRRRRRXXXXXXMMMMMMMMMMMMMM\n" +
                "MMMMMMMYYYYYYYYYYUUUWWWWRLLLUULLQQQXXXFFFFFZZZZZZZZZZZZZKKWWWWIIIIIIIIIIIIIIILLLLLLMMMMMMMMAAHHHEEEEEEEEEEXAAAAAWRRRRRRRXXXXXXXXMMMMMMMMMMMM\n" +
                "MMMMMMYYYYYYYYYYYYYYWWWLLLLLLLXXQQQXXXFFFFFFFFFZZZZZZZZZKKWWWIIIIIIIIIIIIIIIIIILJMLMMMMMMMMMAHHWEEEEEEEEEMMMAAAAARRRRRRIIXXXXXXMMMMMMMMMMMXX\n" +
                "MMMMMRYYYYYYYYYYYYYLWWLLLLLLLLXXQQXXXXXXFFFFFFFKKZZZZZZZKKWWWWIIIIIIIIIIIIIIIAALLMMMMMMMMMMMAAHMTEEEEEEEEMMMMDAAAARRRRIIIIIIXXXXMMMMMMMMMMMM\n" +
                "MMMMLYYYYYYYYYYYYYCCMWRRRLLLLXXXXXXXXXXXFFFFFFFFFZZZZZKKKKKKWIIIIIIIIIIUIVVIAAAAMMMMMMMMMMMMMMMMMEEEEEEEEMMMMMMMAAAARIIIIIIIXIIXXMMMMMMMMMME\n" +
                "MMMMLAAYYYYYYYBYCCCCCWRLLLLLXXHXXXHHXXXFFFFFFFFFZZZZZZKKKKKKIIIIIIIIIIIIVVVVVAAAMMMMMMMMMMMMMMMMMEEEEEEEMMMMMMMBBAAAAAAIIIIDIIIIIMMMMMMMMMME\n" +
                "PPMMAAAYYYYMAAAAACCCCCRCLMLMHHHXXXHHHXXFFFFFFFFFFFZZKTTTTTTTTTAIIIIIIIIVVVVVVAAAAAAMMMMMMMMMMMMMMEEEEEEEMMMMMMMBBBBAAAAAUXIIIIIIIMIIIMMMMMEE\n" +
                "FAAAAAAAYYYYAAAAACCCCCCCCMMMHHHHHHHHHHHFFFBFFFFFFKKKKTTTTTTTTTIIIIIIIIVVVVVVAAAAAAAAAAAMMMMMRMRMVVVEREEEMMMMMMMBBBAAAAUAUXXXXXXIIIIIIIGGMEEE\n" +
                "FAAAAAAAAKYYAAAAACCCCCCCCCCMMHHHHHHHHHHPFFFFFXQFTTKKKTTTTTTTTTIIIIIISSVVVVVVVVAAAAAAAHHMMMMMRRRREEEERERMMMMMMMMBBBBBBAUUUUUUUXXIIIIIIIIMMMEE\n" +
                "FFFAAAAAAAAAAAAACCCCCCCCCCCMHHHHHHHHHHHFFFFJXXTFTTTTTTTTTTTTTTIIIIIIIIIVVVVVVVAAAAAAAHHHHHHHHRRRRRRRRRRRMMMMMMMBBBBBBBUUUUUXXXXIIIIIIIIEEMEE\n" +
                "FFAAAAAAAOAAAAACCCCCCCCCCCCCHHHHHHHHHHHJFFFXXTTTTTTTTTTTTTTTTTIIIIIIIIIIVVVVVVAAAAHHHHHHHHHHHRRRHRRRRRRMMMMMMMMMBBBBBBBBUUUUIIIIIIIIIIIIEMEE\n" +
                "FFFFFAAAAFFAFXXXCCCCCCCCCCCCFFHHHHHHHHHHXXXXXXETTTFTTTTTTTTTTTTIIIIIIIIIVVVVVAAAAAAAHHHHHHHHHHRHHHRRYYYIKKMMMMMMBBBBBBBUUUUUUIIIIIIIIIIEEEEZ\n" +
                "FFFFFFFFFFFFFEEXECCCFCCCFFCCFFNHHHHHHHHHXXXXXXETTTTTKTTTTTTTTTTIIIIIIIIIVVVVVAAAAAAHHHHHHHHHHHHHHHHYYYKKKMMMMMUMMBBBBBUUUUUUUYIIIIIIIIIIEZZZ\n" +
                "FFFFFFFFFFFFFEEEEFFFFFCFFFFFFFHHHHHHHHHXXXXXXXXXTTTTTTTTTTTTTTTTTTIIIIIIVVVAVAAAAAAAHHGHHHHHHHHHHYYYYYNNNMMMMUUUBBBUBUUUUUUUUUIIIIIIIIIIIZZZ\n" +
                "FFFFFFFFFFFFFEEEEFFFFFFFFFFFFFYHHHHHHXXXXXXXXXXXTRRTTTTTTTTTTTTTTTTIIIIIVVVAAAAAAAWWWWWWWWWWHHHHHYYYYYYNNMMMMUUUUBUUUUUUUUUUXXIIIIIIIIIIIIIZ\n" +
                "FFFFFFFFFFFFFEEEEEFEEFFFFFFFFFFFHHHZHXXXXXXXXXXXRRRKKTTTTTTTTTTTTTTIAIAIIIIAAAAAAAWWWWWWWWWWHHHHHYYYYYYYYYYYYUUUUUUUUUUUUUUUXIIIIIIIIIIIIICE\n" +
                "FFFFFFFFFFFXFEEEEEEEEFFFFFFFFFFFHHZZXXXXXXXXXXXXRRKKKKKKTTTTTTTTTTTIAAAIIIAAAAAALLWWWWWWWWWWHHHHHYYYYYYCCCYYYYPUUUUUUUUUUUUUXXIIIIIIIIIIICCC\n" +
                "FFFFFFFFFFFFEEEEEEEEEFFFFFFFFFFFHHZXXXXXXXXXXXXXRRRKKKZZTTTTTTTTTTTITAAAAAAAAAAALLWWWWWWWWWWWWWHHYYYYYYCCCYYPYPUUUUUUUUUUUUUUXIIIIKIIIIIISCC\n" +
                "FFFFFFFFFFEEEEEEEEEESFFFFFFFFFFFFXXXXXXXXXXXXXXXRRRKKRUUUUUTTTTTTTTTTAAAAAAAAAAAALWWWWWWWWWWWWWWWYYYYYYCCCYYPPPUPPUUUUUUUUUUUKIIIIKIIIICSSCC\n" +
                "FFFFFFFFEEEEEEEEEEBFFFFFFFFFFFFFFFFXXXXXPXXXXXXXRRRKRRRUUUUTTTTTTTTTTTTAAAAAAAAALPLLLLLLWWWWWWWWWYYYYYYCCCYYYPPPPPUPUUUUKKKKKKKIIIIIRRRCCCCC\n" +
                "FFFXIFEEEEEEEEEEEBBPFFFFFFFFFFFFFFFFFXXXPXXXXFXXRRRRRRRUUUUTTTTTTTTTTTTAAAAAAAALLLLLLLLLWWWWWWWWWYYYYYYCCCCCCCPPPPPPUKKKKKKKKKKRRRIRRCCCCCCC\n" +
                "XFIIIIIIEEEEEEEEEBBPPPPPPPFPPFZFMMMMMSMLMNXXXXXQRRRRRRUUUUUTTTTTTTTTTTTTAAHHAAALLLLLLLLLWWWWWWWYYYYYYYYCCCCCCCPPPPPPUWWWKKKKKKQRRRRRRRRRCCCO\n" +
                "XXXQIIIIIEEEEEEEEEBPYPPPPMPPPZZMMMMMMMMMMMMXTTXQRRRRRRUUUUUUUUUUUUUTTHHHHHHHHALLLLLLLLLLWWWWWWWYYYYYYYYCCCCCCCPPPPPPWWKKKKKKKKKRRRRRRRRROCCO\n" +
                "XXIIIIIIIIIEEEEEEEEYPPPPMMPZZZZMMMMMWMMMMMMMTTTQQRRRRRRUUUUUUUUUUUUTHHHHHHHHHHMLLLLLLLLLWWWWWWWYYYCCCCCCCCCCCCPPPPPPPWWWWKKKKKKRRRRRRRROOOOO\n" +
                "IIIIIIIIIIIEEEEOOOOPPPPPPPPPZZZMMMMMMMMMMMMMMQQQQRRRRRRUUUUUUUUUUUTTTTHHHHHHHHMLLLLLLLLLFFFFYYYYYYCCCCCCCCCCCCPPPPPPPWWWWKKOORRRRRRRRRRROOOO\n" +
                "MIIIIIIIIIQEEEEPPPPIIIIIIIIIIZZMMMMMMMMMMMMMZZZQQRRRRRRUUUUUUUUUUUTTTHHHHHHHMMMMLLLLLLLFFFFFYYYYYYCCCCCCCCCCCCSSPPMMBBBBBOOOOORRJRRRRRRRROOO\n" +
                "MMIIIIIIIFFEEEEAAAAIIIIIIIIIIIIIIIIIIMMMMMQMRRZQQQQRRRRRUUUUUUUUUTTTTHHHHHMMMMMLLLKKLLLFFFFFYCCCCCCCCCCCCCCCCCSSSSSMMBBBBOOOOOORRRRRRRRROOOO\n" +
                "MMIIFIFPFFFEEEEEAAPIIIIIIIIIIIIIIIIIIMMMMMRRRQQQQQQQQRVRUUJUUUUUUTTTTHHHHHHMMMMMLJJKJQLLFFFFYYCFFFCCCCCCCCCCCCSSSSSBBBBBBOOOOORRRRRRORRROOOO\n" +
                "FFFFFFFFFFQQQEAAAAAIIIIIIIIIIIIIIIIIIMMMMMRRRRQQQQPPVVVVJJJJUUJUTTTTTTTHHHTTMMMJLJJJJFFFFFFFFFFFFNCCCCCCCCCCSSSSZZSSBBBBBOOOOOORRRAROOOOOOOO\n" +
                "FFFFFFFFQQQQQQUAAAAIIIIIIIIIIIIIIIIIIMMQMMMRRRRQQQPVVVVVJJJJJJJUTTTTTTTTHHTTMMMJJJJJJFFFFFFFFFFFFNCCCCCCCCCCCCCCZZZBBBBBBBOOOORRRRAROOOOOOOO\n" +
                "FFFFFFFFFQQQQQUAAAAIIIIIIIIIIIIIIIIIIMMQQRRRNRQQQPPPPVVVVJJJJJWTTTTTTTTTTTTTTLJJJJJJFFFFFFFFFFFFFSCCCCCCCCCCCCCCZMBBBBBBBBNNNNEERAAACOOOOOOO\n" +
                "FFFFFFFFFFFFQUUUAUUIIIIIIIIIIIIIIIIIIIIQQQQRQRQQQVVPVVVVVJJJJWWWTTTTTTTPTTTTTLJJJJJBBFFFFFFFFFFFFSCCCCCCCCCCCCCCZMMMBBBBBBBNNNNNNACCCOCCOOOO\n" +
                "FFFFFFFFFFFWUUUAAUUIIIIIIIIIIIIIIIIIIQQQQQQQQQQQQQVVVVVVVJJWWWWWWTTTTTPPTTTTTLJJJJLBLFFFFFFFFFFFSSSSSSSCCCCCCCCCMMMMBBBBBBBBNNNNAACCCCCCCCOO\n" +
                "FFFFFFFFFFFWUUUUUUUUUUUUUUPFFIIIIIIIIQQQQQQQQQQQQQVVVVVVVVJJWWWWWTTTPPPTTTTLLLLJLLLLLIFFFFFFFFFFFSSSSSACCCCCCCCCMMMMBBBBBTNNNNNNNACCCCCCCCCC\n" +
                "FFFFFFFFEFFWUUUUUUUUUUUUUUFFFIIIIIIIIQQQQQQQQQQQQVVVVVVVVVVWWWWWWWTTPPPLTTLLLLLLLLLLLLLFFDDFFFFSSSAASSACCCCCCCCCMMMMBBBBBTNNTNNNNNICCCCCCCCC\n" +
                "WFFFFFFFEFFEPPUUUUUUUUUUUUUFFFFFFMMMQQQQQQQQQQQQQVVVVVVVVVVVWWWWWTTWLLPLTTLLLLLLLLLLLLDFFDDFDFFSTSAASAACCCCCCCCCMMMMBBTBBTTTTVNNNIICCCCCCCCC\n" +
                "FFFFFFEEEEEEPPUUUUUUUUUUUUFFFFFFMMQQQQQQQQQQQQQQVVVVVVVVVVOVTWWWWWWWWLLLLLLLLLLLLLLLLDDDDDDDDFFSTAAAAACCACCCCCCCMKMMBBTTTTTTTTTIIICCCCCCCCCC\n" +
                "IIFFFEEEHEPPPPUUUUPUUUUUUUFFFFFFFFQQQFFFFFFFFFQQQVVVVVVVVVVVTWWWWWWWWWWLLLLLLLLLLLLLLLLDDDDDDTTTTTTAAAACACCCCCCCMBMKBTTTTTTTTTTIIIICCCCCCCCC\n" +
                "IIIFFFFEFPPPPPPUUUUUUUUUUUFFFFFFQQQQQFFFFFFFFFVQVVVVVVVVVVVVVWWWWWWWWLLLLLLLZLLLLLLLLLLDDDDDDDTXTTTTTTAAACCCCCCCBBBBBDTTTTTTTTTIIIICCCCCCCCC\n" +
                "IIYFFFFFFPPPPPPPPFFFFUUUUFFFFPFFQQNNNFFFFFFFFFVVVVVVVVVVRRRVVWWWWWWWWWLLLLLLZLLLLLLLDDDDDDTDTTTTTTTTTTTTACCCCCCCABBBBBTTTTTTTTIIIIIICCCCCCZZ\n" +
                "IIYFFFFFPPPPPPPPPFFFFXXUUFFPPPPPNNNNNFFFFFFFFFVVVVVVVVVVRRWVWWWWWWWWWWLLLLLLZLLZZZZDDDDDTTTTTTTTTTTTTTTTTCCCCCCCAAABAATTTTTTTIIIIIIICCCCCCZZ\n" +
                "IIYYFFFFFPPPPPPPPFFFFXXXUUXNPPPPNNNNNFFFFFFFFFZPVVVVVVVVRRWWWWWWWWWWTTLLLLLLZZZZZZZDDDDDTGTTTTTTTTTTTTTTTCCCCCCCAAAAATTTTTTTTIIIIIIICCCCCCZC\n" +
                "XRYYYYFPPPPPPPPPPFFFFXVXXXXNPPNNNNNNNFFFFFFFFFPPVVVVVVVVRRWWWWWWWWWWTTLLLLLZZZZZZZSSDDDDTTTTTTTTTTTTTTTTTCCCCCCCAAGJJTTTTTTTIIIIIIIICCCCCCCC\n" +
                "XRRRRYYPPPPPPPPPPFFFFFFFFFXNNNNMNNNNNFFFFFFFFFPPPVVVVVVVWWWWWWWWWTTTTTLLLLLLZZZZZZSSDSDDTHTTTTTTTTTTTTTTTTAAAAAAAAGJJTTTTTTIIIIIIIICCCCCCCCC\n" +
                "XXXRBRRPPPPPPPPPPFFFFFFFFFFFFFFFFFFNNFFFFFFFFFFFPVVVVVVVTWWWWWWWTTTTTTTTLLLLZZZZZZZSSSSSTTTTTTTTTTTTTTTTTTAAAXAGJGGGJGTTTGIIIIIIIIIIICCCCCCC\n" +
                "XXXRRRRPPPPPPPPPPFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFJJVEVTTTVTWWWWWWTTTTTTTTLLLLLDZZZZZZZSSSSSSTTTTTTTTTTTTTIIAAAXXGGJGGGGGXXGGIGIIIIIIIIICCCDDCC\n" +
                "XXXLRRXPPPXXPPPPPVVFFFFFFFFFFFFFFFFFFFFFFFFFFFJJJJETTTTTTTTWTTTTTTTTTTLLLLLLDZZZZZZZSSSSSSYLTTTTLLTTTTTTTAAXXXXGJGGGGGGXGGGGGIIIIIIDDDDDDDDD\n" +
                "XLXLLLXXXXXXXXPPVVVFFFFFFFRRNNNFFFFFFFFIIIIIJJJJJEEETTTTTTTTTTTTTTTTTTTTMLLWDDZZZZZZSYSYYYYLTTTTLLLLTTTVVXXXXXGGGGGGGGGXGGGGIIIIIIIDDDDDDDDD\n" +
                "XLLLLLLLXXXVXXPVVVVVVVVVVTERNNNFFFFFNNIIIIIJJJJJJJEETTTTTTTTTTTTTTTTTTTXMMLMRDZZZZZZYYYYYYYLLLLLLLLLLTVVNNNXXXXGGGGGGGGGGGGGIIIDIIDDDDDDDDDD\n" +
                "LLLLLLLLLXXVXXPVVVEEEVVEEEERRNNFFFFFNNIIIIIIJJJJIIIEETTTTTTTTTTTTTTTTTXXMMMMZZZZZZZZYYYYYYLLLLMLLLLLLLVVNNNXXGJGGGGGGGGGGGGGIDDDDDDDDDDDDDDD\n" +
                "LLLLLLLVVVVVVVVVVVVVEEVEEEERNNNFFFFFNIIIIIIIIIIIIIIIEEEBTTTTTTTTTTTTMXXXXMMMMZZZZZZZZYYYLLLLLMMLLLLLLLNNNNNXGGGGGGGGGGGGGGGLIDDDDDDDDDDDDDDD\n" +
                "LLLLLLLLVVVVVVVVVVVVVEEEEERRRRRRRNNLLLIIIIIIIIIIIIIIIEBBTTTTTTTTTTMMMXMMMMMMMZJZZYZZZZYYLLLLLLLLLLLLQLDNNNNXXGGCCGGGGGGGGGULLLDDDDDDDDDDDDDD\n" +
                "ALLLLLLVVVVVVVVVEVVVEEEEEHEERRERRNNLLLLLIIIIIIIIIIIIIFZBBSTTTTTTTTMMMMMPMMMMMZZZYYYZYYYYYLLLLLLLLLLQQQQQNNNCCCCCGGGGGGGGWGLLRNDRRRDDDDDDDDDD\n" +
                "LLLLLLLLLVVVVVVEEEEVVEEEEEEEEEERRRRLLLLLIIIIIIIIIIITTFFBBBTTTTTTMMMMMMMMMMMMVZEZYYYYYYYYLLLLLLLLLLLQQQQNNNNCCCCCGGGGGGLLWLLLRRRRRRRRDDDDDDDD\n" +
                "LLLLLLLLLLVVVVEEEEEEEEEEEEEEEEERRLLLLLLLLLIIIIIIIIIIIFFQQBBTTTTTMMMMMMMMMMMMMMEZYYYYYYYYYLLLLLLLLQQQQQQWWNNCCCCCGCCGCCLLLLLLRRRRRRRRRDDDDDDD\n" +
                "LLLLLLLLLLVVVVAAAEEEEEEEEEYEEEELLLLRRRRRRRIIIIIIIIIIIIFQQQQTTTTWWMWMMMMMMMMMMMMYYYYYYYYYYYLDEELLLQQQQQQQWWBCCCCCCCCCCCLLLLLLLRRRRRRRRDDDDDDD\n" +
                "LLLLLLLLLLVVVVAAAEEEEEEEEYYEYYLLLLLRRRRRRRLIIIIIIFFIFFFQQQLLTWWWWWWMMMMMMMMMMMMYYYYYYYYYYYYEEELLLQQQQPPQBWBCBCCCCCCCCCLLLLLLLLRRRRRRRRRRDDDD\n" +
                "LLLLLLLFLLVVMLAAAAEEEEEEEYYEYYLLLLLRRRRRRRLIIIIIIFFFFFFLLLLWWWWWWWWMMMMMMMMMMMMMYYYYYYYYYYYEEPLLLQQQQPBBBBBBBBCCCCCCCCCLLLLLLLRRRRRRRRRDDDDD\n" +
                "LLLFFFFFFLVLLLAAAEEEEEEEEEYYYYLLLLLRRRRRRRIIIIIIIFFFFFFLLLLLWWWWWWWMWMMMMMMMMMMMYYYYYYYYYYEEEPELLPPPQBBBBBBBBBCCCQQCCCLLLLLLLLLTTTLRLRRRRDDR\n" +
                "LLFYFFFFFLLLLAAAEEEEEEEEYYYYYYLLLLLRRRRRRRIIIIIIIFFFFFFFLLLLLWWWWWWWWWMMMMMQPMMMYYYQQYYYYYEEEEEPLPPPBBPBBBBBBBBCCQQQQCCLLLLLLLLLTTLLLLDDDDDD\n" +
                "FFFFFFFFFLLLAAAAJJEEEEEEEEYYYLLLLLLRRRRRRRUIIDIIIFFFFFLLLLLLLWWWWWWWWWWWMMPQQMMQQQQQQQYNNNEEEPPPLPPPPPPBBBBBBWQQQQQQQQLLLLLLLLLLTLLLLLLDDDDD\n" +
                "FFFFFFFFFLLLLAAAJJJJJEEEEEJYYYLLLLLRRRRRRRUUIULLIIFFFLLLLLLLLLWWWWWWWQQQQMPQMMMQQQQQQYYNNEEEENPPPPPPPPRCBBBBBQQQQQQQGQLLLLLLLLLLLLLLLLLLDDDQ\n" +
                "FFFFFFFFFFFLLAAAJJJJJJJJEJJYLLLLLLLRRRRRRRRRUUULFIFFFFLLLLLLLLWWWWWWWQQQQQQQQQQQQQQGGGNNNNEZNNPPPPPPPPRRRBBBQRQQQQQQQQQLLLLLLLLGLLLLLLLLDDQQ\n" +
                "FFFFFFFFFFFFAAAAJJJJJJJJEJJYYLLLRRRRRRRRRRRRUUUUFFFFFFLLLLLLLLLWAWWWWWQQQQQQGGGGGGGGGGNNNNENNNPPPPPRPPRRRRKBQQQQQQQQQQQQQLLLLLGGLLLLLLLLDQQQ\n" +
                "FFFFFFFFFFFFAAAAAAJJJJJJJJJYYLLLRRRRRRRRRRRRUUUFFFFPPFFPLLLLLLAAAWWWWWQQQQQQGGGGGGGGGGNNNNNNNNPPPPPRRPRRRRKKKKQQQQQQQQQQQLLLLGGGGGLLLLLLKQQQ\n" +
                "FFFFFFFFFFFFFFFAJJJJJJJJJJJJYLLLRRRRRRRRRRRRUUUFFFFPPPPPLLLLLLAAAAWWWCQCCQQQGGGGGGGGGGNNNNNNNNNNPPPRRRRRRRKKKQQQQQQQQQQQLLGLLGGGGGLLLKKKKQKQ\n" +
                "FFFFFFFFFFFFFFFFJJJJJJJJJJJJYYYLRRRRRRRRRRRRGUFFFFPPPPPPALLAAAAAACCCWCCCCCQCGGGGGGGGGGNNNNNNNNNNPPRRRRRRRRKKKQQQQQQQQQQQQGGGGGGGGGLLKKKKKKKK\n" +
                "FFFFFFFFFFFFFFLFJJJZZJJJJJJJJYYJRRRRRRRRRRRRUUFFPPPPPPPPPQAAAAAAAACCCCCCCCCCGGGGGGGGNNNNNNNNNNNKNRRRRRRRRKKKKKQQQQQQQQQQGGGGGGGGGGGLLKKKKKKK\n" +
                "FFWFFFFFFFFFFLLLLJJJZJJJJJJJJYYJRRRRRRRRRRRRSSFFPPPPPXXXXXXQQAAACCCCCCCCCCCCGGGGGGGGNENNNNNNNNNNNRRRRRRRKKKKKKKKQQQQQSGQGGGGGGGGGGGKKKKKKKKK\n" +
                "FWWFFFFFFFFFHLLLLHBBJJJJJJJJYYJJRRRRRRRRXXXXXPPYPPPPPXXXXXXXXXXXUUACCCCCCCCCCCCGGGGGQEEENNNNNDWNERRRRRKKKKKKKKKKKKQQSSGGGGGGGGGGGGKKBKKKKKKK\n" +
                "WWFFFWWWHFFHHHHHHHJJJJJJJJJJJJJJJJJJJJJRXXXXXPPPPPPPPXXXXXXXXXXXUUACCCCCCCCCCCCGGGGGEEEENNNNNWWPEEERRRKKKKKWWKKKKKQQQQGGGGGGGGGGGGKKKKKKKKKK\n" +
                "WWOOWOWWHHHHHHHHHGGGGJJJJJJJJDJJJJJJJJJJXXXXXWPPPPPPPPXXXXXXXXXXUUCCCCCCCCCCCCCGGGGGEEEEEENNHHWWEEEKKKKKKKWWWWKJJJJJJJGGGGGGGGGGGGKKKKKKKKKK\n" +
                "WWWOOOOHHAHKHHHHHHGGJJJGJJDDDDJJJJJJJJJJXXXXXPPPPPPPUUXXXXXXXXXXUUCCCCCCCCCCCCRGGGGGEEEEEEWWWWWHHEEEEEKKKKWWWWWJJJJJJJGGGGGGGGGGGGKKKKKKKKKK\n" +
                "WWWOOOOOHHHHHHHHHHGGGGGGGGDDDJJJJJJJVVJJXXXXXXXXXXXXXXXXXXXXXXXXUUCCCCCCCCCRRRRRRRRREEEEEWWWWWWHHEEEEEKEEEWWWWWWJJJJJJJJGGGGGGGGGGGKKKKKKKKK\n" +
                "OOOOOOOOOOHHHHHHHHHHGGGGGGGDDJDJDJJJVVJVXXXXXXXXXXXXXXXXXXXXXUUUUUAAACCCCCRRRRRRRRRREEEEEWWWWWWWHHEEEEKEEWWWWWWYJJJJJJJJGGGGGGVVGVVLKBKKKKKK\n" +
                "ROOOOOOOOOHHHHHHHHHHGGGGGGGGDDDDJJJJJVVVXXXXXXXXXXXXXXXXXXXXXUUUUUACCCCCCRRRRRRRRRRRRREEWWWWWWWWWEEEEEKEEWWWWWWYYJJJJJJJGGGGGVVVVVVVVKKKKKKK\n" +
                "RROOOOOOOOHHHHHHHHHHHGGGDDGGDDDDDDDJVVVVVVVVXXXXXXXXXXXXXXXXXUUUUUACCCCCCCRRRRRRRRRVVVDEWWWWWWWWEEEEEEKEEKKWWSSJJJJJJJJGGGGGGVVVVVVVVKKKKKKK\n" +
                "RROOOOOOOOHHHHHHHHHHXGXGDDDDDDDDDDDDVVVVVVVVXXXXXXXXXXXXXXXXXUUUUUCCCCCCCCCCRRRRRRRVVVDEEWWEEEEEEEEEEEEEEKKWWSSJJJJJJJJJJGGJVVVVVVVVVVYKKKKK\n" +
                "ROOOOOOOOOOHHHHHHOHXXXXXUDDDDDDDDDDDDVVVVVVVXXXXXXXXXXXXXXXXXAAAACCCCCCNCMMRRRRCCRVVVDDDEWWEEEEEEEEEEEEEEEESSSSJJJSJJJJJGGJJVVVVVVVVVKKKKKKK\n" +
                "OOOOOOOOOOOHHHOHOOOUUUUUUDDDDDDDDDDDDVVVVVVVXXXXXXXXXXXXXXXXXAAAAAAAACNNNRRRRRRICCVVVVDEEEEEEEEEEEEEEEEAAEEESSSSSSSSSJJJJJJJBGVVVVVVVKKKKKKK\n" +
                "OOOOOOOOOOOOHHOOOOOUUUUUUUDDDDDDDDDDVVVVVVVVXXXXXXXXXXXXXXXXXAAAAAAAAAANNNNRCCCCCCVVVDDDEEEEEEEEEEEEEEEESSSSSSSSSSSSSJJJJJJJBBBSSSVVVKKKKKKK\n" +
                "OOOOOOOOOOOOHOOOOUUUUUUUUUUDDDDDDDDDVZVVVVVVVVYHXXXXXXXXXXXXXRRRAAAAAAANNNZCCCCCCCDDDDDDDEEEEEEEEEEEEEEESSSSSSSSSSSSSJJJJGJJBBBBSGKKKKKKKKKK\n" +
                "OQOOOOOOOOOOOOOOOUUUUUUUUUUDDDDDDDDDVVVVVVVVVVVYXXXXXXXXXXXXXRRRRRAAAAZNNZZCCCCCCVDDDDDDDDDEEWEEEEEEEEEAAAASSSSSSSSSSJJJJGJGGGBGGGKKYKKKKKKK\n" +
                "MQOOOOOOOOOOOOOOOUNNUUUUUUUUUUDDDDDDVVVVVVVVVVVVXXXXXXXDRRRRRRRRRIZZAZZZZZZZCCCCVVVDDDDDDDEEEWEWEEEEEEEKAAASSSSSSSSSSSJJGGGGGGGGGGYYYKKKKKKK\n" +
                "QQOOQQOOOOOOOOOOONNNUUUUUUUUUDDDVDDDDDVVVVVVVVDDXXXXXXXDRRRRRRRRRIZZZZZZZZZCCCCCCVDDDDDDDDZZWWWWWWWEEEOKAAASSSSSSSSSJJJGGGGGGGGGGYYYYKKKKYYK\n" +
                "QQOQQQOOQOOOOOOOOVUUUUUUUUUUUVDDVDDDDDDDVVVVVVVVXXXXXXDDRRRRRRRROZZZZZZZZZZZCCCVVVDDDZZDZZZZWWWWWWWWWOOOOAAASSSSSSSJJGGGGGGGGGGGZYYYYYKYYYKK\n" +
                "QQQQQQOQQQOOOOOVVVEVIIUJJUUUUVVVVDZDDDDDVVVVVYYDDDDDDDDDRRRRRRRRZZZZZZZZZZZZZNCOOOOZZZZZZZZZWWWWWWWWWWOOOAAOSOSSSSSSGGGGGGGGGGGGYYQYYYYYYYYY\n" +
                "QQQQQQQQQQKQQQOOVVVVVVJJJJJJVVVVVDDDDDDVVVVVYYYDDDDDDDDDQRARRRRZZZZZZZZZZZZKKKKKKKKZZZZZZZZZWWWWWWOOOWWOOOOOOOSSSSOOGGGGGGGGGGGGYYYYYYYYYYYY\n" +
                "QQQQQQQQQQQQQQOOOVVVVJJJJJJJJVVVVDDDDDDDVVVYYYJDDDDDDDDDDRRRRRRRRZZZZZZKKKKKKKKKKKKZZZZZZZZWWWOWWWOOLWWOOOOOOOSOOSOOGGGGGGGGGGGGGYYYYYYYYYYY\n" +
                "QQQQQQQQQQQQOOOOOOOVOOJJJJJVVVVVVVDDDDDDDVOJJJJAADYYDMDDDRRRRRRRRZZZZZZKKKKKKKKKKKKKKKKZZZZWWWOOWOOOOOOOOOOOOOSOOSOOGGGGGGGGGGGGGYYYYYYYYYYY\n" +
                "QQQQQQQQQQOQOOOOOOOOOJJJJJJVVVVVVVVVDDDDDDJJJJJJJJYYDMMMMRRRRRYYYZZZZZZKKKKKKKKKKKKKKKKZZZWWOOOOOOOOOOOOBOOOOOOOOOOOGGGGGGGGGGGGGGYYYYYYYYYY\n" +
                "QQQQQQQQWOOOOOOOOOOOOJJJJJVVVVVVVVVDDDDDJJJJJJJJJJMMDDMMMMRMRMYYYZZZZAAKKKKKKKKKKKKKKKKZWWWWOOOOOOOOOOOOOOOOOOOOOOOGGGGGGGGGGGGGGGYYYYYYYYYY\n" +
                "QQQQQQQQWOWOOOOOOOOOOJJJJJVVVVVVVDDDDDDDDDJJJJJJJJMMMMMMMMMMMMYYAAAAAAAKKKKKKKKKKKKKKKKWWWWWOOOOOOOOOOOOOOOOOOOOOOOOGGGGGGGGGGGGGGYYYYYYYYYY\n" +
                "QQQQQQQQWWWWWOOOOVOOOOOOJXOVVVVVVDDLDDDDDDDJJJJJJJJMMMMMMMMMMMMMIAAAAAAKKKKKRRRKKKKZZCZWWWWWOOOOOOOOOOOOOOOOOOOOOOOORGRRGRGGGGGGYYYYYYYYYYYY\n" +
                "QQQQQQYWWWWWOOOOVVOVOOOOOOOVVVVZZLLLLDDDDDDLJJJJJJJJJMMMMMMMMMMAAAAAAAAKKKKKRRRKKKKSZZWWWWWWWWOOOOOOOOOOOOOOOOOOOOORRRRRRRRGGGMMYYYYYYYYYYYY\n" +
                "QQQQQQYWWWWWWWWVVVVVVOOOOOVVAAVLLLLLLLLLDDLLLLJJJJJJJMMMMMMMMMMTTTTDAAAKKKKKRRRAAAEEEZWWWWWWWWOOOOOOOOOOOOOOOOOOORRRRRRRRRGGMGGMYMYYYYYYYYYY\n" +
                "QQQQQQYWWWWWWWWWAVVVVOOOOOVVVVVLLLLLLLLLLLLLLLJJJJJJJMJMMMMMMMTTTTTTTAAKKKKKRRRAAAEEWWWWWWLWLLOOOOOOOOOOOQQQOOOOOORRRRRRRRMMMMMMMMMYYYYYYYYY\n" +
                "QQQQQWWWWWWWWWWWAAAVVOOOOOOVMVRLLLLLLLLLLLLLLJJJJJJJJJJJMMMMMMTTTTTTTRRRRRKKRRRAEEEEEEEEEWLLLLLIOOOOOOOOOMQQOOOOOORRRRRRRMMMMMMMMMMMYYYYYYYH\n" +
                "QWQQWWWWWWWWWWWWWAAVVOOOOCVVVRRRLLLLLLLLLLLLLJJJJJJJJVVVMMMMMMTTTTTTTRRRRRKKRRRIEEEEEEEEELLLLLLIIIOOOOQQQQQQOOOORRRRRRRRRMMMMMMMMMNMYGGGGGGQ\n" +
                "WWWQWWWWWWWWWWWWWWWWDDDOOOOORRRLLLLLLLLLLLLLLLJJJJJJJVVVMMMMVVTTTTTTARRRRRKKRRRREEEEEEEEELLLLLLLQQQOOQQQQQQQOOORRRRRRRRRRMMMMMMMMMMMGGGGGGGQ\n" +
                "WWQQQWWWWWWWWWWWWWWWDDDOOORRRRRRRLRRLLLLLLLLLLJJJJJJVVVVVVVMVVVVTTHXXRRRRRRRRRRREEEEWEEEELLLLLIQQQQOQQQQQQQQQOOORRRRRRRRRMMMMMMMMMMMMGQQGQQQ\n" +
                "WQQWWWWWWWWWWWWWWWWDDDOOOOAAAAARRRRRLLLLLLLLLJJJJJJJVVVVVVVVVVVTTHHXXRRRRRRRRRRRIEEEEEEELLLLLQIQQQQQQQQQQQQQQOORRRRRRRRRRRMMMMMMMMMMMQQQGQQQ\n" +
                "WQWWWWWWWWWWWWWWAWWDDXOXSSSSAAAARRRRLLLLLLWLLLJJJJVVVSSSSVVVVVVHHHXEXRRRRRRRRRRRIEEEELELLLLLLQIQQQQQQQQQQQQQQQQJRRRRRRRRRRMMMMMMMMMMLLQQQQQQ\n" +
                "WWWWWWWWWWWXXWWWAAXXXXXXSSSAAAAARRRLLLLLLLLULJJJJJJVVSSBSVVVVVVVXXXXXRRRRRXIIRRRLEEEELELLLLLQQQQQQQQQQQQQQQQQQJJJRRRRRRRRRMMMMMMMMMMMMQQQQQQ\n" +
                "WWWWWWWWWWWXXXWWAXXXXXXXKSAAAAAARRRLXLLLLLLLLLLBJJSVVSSSSSVVVVVXXXXXXRRRRRXXIIILLLLLELLLLLLLQQQQQQQQQQQQQQQQQQJJRRRRRRRRRMMMMMMMMMMMMMQQQQQQ\n" +
                "WWWWWWWWWXXXXXXXXXXXXXXXAAAAAAAAAAASLLLLLLLLLLLLPPSSVSSSSSSSSVVXXXXXXRRRRRXXIIILLLLLLLLLLLLLLQQQQQQQQQQQQQQQQJJJJRRRRRRRRRMMMMMMMMMMMMMQQQQQ\n" +
                "WWWWWWWWWWXXXXXXXXXXXXSSAAAAAAAASASSLLSSSLLLLLLLLLSSTSSSSSQSQQVXXXXXXRRRRRXXXXLLLLLLLLLLLLLLLLLLQQQQQQQQQQQQJJJJJRRRRARRRAAAMMMMMMMMCCQQQQQQ\n" +
                "WWWWWWWWWWXXXXXXXXXXXSSSAAAAAAASSSSSSSSSLLLLLLLLSSSSSSSSSSQQQQXXXXXXXXXXXXXXXLLLLLLLLLLLLLLLLLLLLQQQQQQSQQQQQJJJJRRRAAARRAAAAMMMMMMCCCCCCQQQ\n" +
                "WWWWWWWWWWXXXXXXXXXXXSSSASSAAAASSSSSSSSSSLLSSSSLLSSSSSSSSSQQQQXXXXXXXXXXXXOOOLLLLLLLLLLLLLLLLLLLLQQQQQQSSSQQQJJJJRRRAAAARAAAMMMMMCCCCCCCCCCQ\n" +
                "WWWWWWWWWXXXXXXXXXXXXXXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSQQQQXXXXXXXXXXXXOOOLLLLLLLLLLLLLLLLLLLQQQQQSSSSSQJJJJJJJRRAAAAAAAAMMMMMCCCCCCCCCCC";

        String input1 = "RRRRIICCFF\n" +
                "RRRRIICCCF\n" +
                "VVRRRCCFFF\n" +
                "VVRCCCJFFF\n" +
                "VVVVCJJCFE\n" +
                "VVIVCCJJEE\n" +
                "VVIIICJJEE\n" +
                "MIIIIIJJEE\n" +
                "MIIISIJEEE\n" +
                "MMMISSJEEE";

        char[][] grid = parseInput(input);

        System.out.println(search(grid));
    }
}
